version: '3.8'

services:
  backend1:
    build: ./backend1
    volumes:
      - ./backend1:/app
      - ./data:/app/data
    ports:
      - "3000:3000"

  backend2:
    build: ./backend2
    volumes:
      - ./backend2:/app
      - ./data:/app/data
    ports:
      - "3001:3001"
