
version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdb
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - db_data:/var/lib/postgresql/data

  backend1:
    build: ./backend1
    environment:
      DB_HOST: db
      DB_USER: youruser
      DB_PASSWORD: yourpassword
      DB_NAME: yourdb
    depends_on:
      - db
    volumes:
      - ./backend1:/app
    ports:
      - "3000:3000"

volumes:
  db_data:
